Add shopify tables
turbot/steampipe-plugin-shopify pull request #22
Opened 2023-05-18 13:52 UTC by Priyanka-Chatterjee-2000

* Add shopify_product

* Add more columns to table shopify_product and example queries to docs

* Add limit

* doc update

* Update table name

* Add metafields

* Update product.go

* update descriptions

* Update description of product

* fix extra spaces

* Update doc queries

* Update doc query

* Add table shopify_product_variant. Closes #12 (#17)

* Add shopify_product_variant

* Update shopify_product_variant

* Remove shouldRetryError function

* Add shopify product variant description

---------

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2023-05-22 15:12 UTC, madhushreeray30 requested changes
Please have a look at the suggested changes. Thanks!

2023-05-22 15:12 UTC, madhushreeray30 commented on shopify/table_shopify_product_variant.go
> +		plugin.Logger(ctx).Error("listProductVariant", "connection_error", err)
```suggestion
		plugin.Logger(ctx).Error("listProductVariants", "connection_error", err)
```

2023-05-22 15:12 UTC, madhushreeray30 commented on README.md
> +
```suggestion

### Install

```

2023-05-22 15:12 UTC, madhushreeray30 commented on docs/index.md
> +## Get started
```suggestion
## Quick start
```

2023-05-22 15:12 UTC, madhushreeray30 commented on docs/index.md
> +Environment variables are also available as an alternate configuration method:
```suggestion
Alternatively, you can also use the standard Shopify environment variables to obtain credentials **only if other arguments (`shop_name ` and `token `) are not specified** in the connection:
```

2023-05-22 15:12 UTC, madhushreeray30 commented on docs/index.md
> +- `SHOPIFY_API_TOKEN`
```suggestion
```sh
export SHOPIFY_SHOP_NAME= theshop
export SHOPIFY_API_TOKEN=shpat_ab0a4zaa19c3faketoken924176b387d
```

2023-05-22 15:13 UTC, madhushreeray30 requested changes
Please have a look at the suggested changes. Thanks!

2023-05-23 11:39 UTC, madhushreeray30 commented on shopify/shopify_draft_order.go
> +
```suggestion

// HYDRATE FUNCTION
```

2023-05-29 14:52 UTC, misraved approved these changes

2023-05-29 14:52 UTC, misraved approved these changes

2023-05-29 14:52 UTC, merged